#!/bin/sh

npm run build
aws s3 sync public/ s3://einabit-website/

aws cloudfront list-distributions | \
jq .DistributionList.Items[].Id | \
while read ID; do \
  aws cloudfront create-invalidation \
    --distribution-id $(echo $ID | tr -d '"') \
    --paths "/*"; done
