    <div class="footer-line"></div>
    <section class="footer">
      <div class="dflex jct-between">
        <div class="footer-logo">
          <p>
            EINABIT LABS S.L. Xixona, 8. 03802 Alcoi/Alacant Spain<br/>
            <a class="mailto" href="mailto:info@einabit.com">info@einabit.com</a>
            <span id="cpright-year">&copy; </span>
          </p>
        </div>
        <div class="dflex vflex jct-center">
          <a class="ext icon-linkedin" href="https://www.linkedin.com/company/einabit/">
          </a>
          <a class="ext icon-github" href="https://github.com/orgs/Einabit/repositories">
          </a>
        </div>
      </div>
    </section>
    <script type="text/javascript">
      document.querySelector("#cpright-year").innerHTML += new Date().getFullYear();
    </script>
  </body>
</html>
