    <div class="footer-line"></div>
    <section class="footer">
      <div class="dflex jct-between">
        <div class="footer-logo">
          <span>
            EINABIT LABS S.L. Xixona, 8. 03802 Alcoi/Alacant Spain
          </span>
          <br/>
          <span>
            <a class="mailto" href="mailto:info@einabit.com">info@einabit.com</a>
            <span id="cpright-year">&copy; </span>
          </span>
        </div>
        <div>
          <a class="ext" href="https://www.linkedin.com/company/einabit/">
            <img src="icons/PNG/icono-footer-01.png">
          </a>
          <a class="ext" href="https://github.com/orgs/Einabit/repositories">
            <img src="icons/PNG/icono-footer-02.png">
          </a>
        </div>
      </div>
    </section>
    <script type="text/javascript">
      document.querySelector("#cpright-year").innerHTML += new Date().getFullYear();
    </script>
  </body>
</html>
