    <div class="footer-line"></div>
    <section class="footer">
      <div class="dflex jct-between">
        <div class="footer-logo">
          <p>
            <a href="tel:+34633423169">📞 +34 633 42 31 69</a><br />
            <a class="mailto" href="mailto:info@einabit.com">✉️ info@einabit.com</a><br/>
            EINABIT LABS S.L. <span id="cpright-year">&copy; </span>
          </p>
        </div>
        <div class="dflex vflex jct-evenly">
          <a class="ext icon-linkedin" href="https://www.linkedin.com/company/einabit/">
          </a>
          <a class="ext icon-github" href="https://github.com/orgs/Einabit/repositories">
          </a>
        </div>
      </div>
    </section>
    <script type="text/javascript">
      document.querySelector("#cpright-year").innerHTML += new Date().getFullYear();
    </script>
  </body>
</html>
