<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Einabit, integración con sensores, industria 4.0</title>
    <link rel="stylesheet" href="global.css">
    <link rel="stylesheet" href="layout.css">
    <link rel="icon" href="img/Tuerca_Color.png">
  </head>
  <body>
    <section class="header">
      <logo>
        <img src="img/Logo_Einabit_Color.png" />
      </logo>
      <nav>
        <div>
          <a title="Qué hacemos?" href="index.html">Inicio</a>
        </div>
        <div>
          <a title="Quieres hacer proyectos IoT?" href="develop.html">Desarrollo</a>
        </div>
        <div>
          <a title="Quieres aumentar la eficiencia?" href="industry.html">Industria 4.0</a>
        </div>
        <div>
          <a title="Quién nos avala?" href="clients.html">Clientes</a>
        </div>
        <div>
          <a title="Cuánto cuesta?" href="prices.html">Precios</a>
        </div>
        <div>
          <a title="Cómo funciona?" href="tools.html">Herramientas</a>
        </div>
        <div>
          <a title="Quiénes sois?" href="about.html">Empresa</a>
        </div>
      </nav>
    </section>
